[
    {
        "content": "<p>(This is a cross-post from the mailing list)</p>\n<p>When retrieving local propositions inside a proof and applying standard operations on them (e.g., <code>Thm.unconstrainT</code>), I get the following error (Isabelle2023):</p>\n<blockquote>\n<p>exception CONTEXT (\"No content for theory certificate Scratch:11571\", [], [], [\"True\"], NONE) raised (line 561 of \"thm.ML\")</p>\n</blockquote>\n<p>The problem is easy to reproduce, e.g. with the following code:</p>\n<div class=\"codehilite\" data-code-language=\"Isabelle\"><pre><span></span><code><span class=\"k\">proof</span><span class=\"w\"> </span><span class=\"o\">-</span>\n<span class=\"w\">  </span><span class=\"k\">have</span><span class=\"w\"> </span><span class=\"n\">True</span><span class=\"w\"> </span><span class=\"ow\">..</span>\n<span class=\"w\">  </span><span class=\"kt\">ML_val</span><span class=\"w\"> </span><span class=\"s\">‹Proof_Context.facts_of @{context} |&gt; Facts.props |&gt; map (Thm.unconstrainT o fst)›</span>\n</code></pre></div>\n<p>This is probably due to compression of some certificates inside this context (where full certificates are replaced by ids). Is there any way to work around this?</p>",
        "id": 392143139,
        "sender_full_name": "Fabian Huch",
        "timestamp": 1695223987
    },
    {
        "content": "<p>So <code>Thm.transfer'</code> does solve the issue (thanks <span class=\"user-mention\" data-user-id=\"302181\">@Simon Roßkopf</span> ), but I still have no clue why this should be necessary.</p>",
        "id": 392147939,
        "sender_full_name": "Fabian Huch",
        "timestamp": 1695225461
    }
]