<html>
<head><meta charset="utf-8"><title>[isabelle] Unexpected Behavior with Isabelle Server 2023 · Mirror: Isabelle Users Mailing List · Zulip Chat Archive</title></head>
<h2>Stream: <a href="http://isabelle.systems/zulip-archive/stream/247541-Mirror.3A-Isabelle-Users-Mailing-List/index.html">Mirror: Isabelle Users Mailing List</a></h2>
<h3>Topic: <a href="http://isabelle.systems/zulip-archive/stream/247541-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Unexpected.20Behavior.20with.20Isabelle.20Server.202023.html">[isabelle] Unexpected Behavior with Isabelle Server 2023</a></h3>

<hr>

<base href="https://isabelle.zulipchat.com/">

<head><link href="http://isabelle.systems/zulip-archive/style.css" rel="stylesheet"></head>

<a name="411702017"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/247541-Mirror%3A%20Isabelle%20Users%20Mailing%20List/topic/%5Bisabelle%5D%20Unexpected%20Behavior%20with%20Isabelle%20Server%202023/near/411702017" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Email Gateway <a href="http://isabelle.systems/zulip-archive/stream/247541-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Unexpected.20Behavior.20with.20Isabelle.20Server.202023.html#411702017">(Jan 08 2024 at 09:44)</a>:</h4>
<p>From: "Joshua K." &lt;<a href="mailto:j.kobschaetzki@campus.tu-berlin.de">j.kobschaetzki@campus.tu-berlin.de</a>&gt;<br>
Hi,</p>
<p>I've recently started working on writing a k6[^0] adapter[^1] for <br>
stress-testing a server compatible with the isabelle server protocol. <br>
The main purpose of the adapter is to analyze the performance <br>
characteristics and behavior of Isabelle server with multiple users and <br>
sessions. During the initial testing phase, I encountered some <br>
unexpected behavior related to the session_stop command. It seems to <br>
trigger a race-condition or edge case, especially when called in quick <br>
succession after start_session, use_theories, and purge_theories[^2] in <br>
a loop. Typically, this occurs on the second to fourth iteration.</p>
<p>Here are the observed stack traces from the Isabelle server's stdout:</p>
<ol>
<li>observed with a single user:</li>
</ol>
<p>Exception in thread "event_timer"<br>
*** Inactive prover input thread for command <br>
"Document.discontinue_execution"<br>
     at isabelle.Exn$ERROR$.apply(exn.scala:25)<br>
     at isabelle.Exn$.error(exn.scala:29)<br>
     at isabelle.package$.$init$$$anonfun$1(ROOT.scala:9)<br>
     at isabelle.Prover.protocol_command_raw(prover.scala:296)<br>
     at isabelle.Prover.protocol_command_args(prover.scala:301)<br>
     at isabelle.Prover.protocol_command(prover.scala:305)<br>
     at isabelle.Protocol.discontinue_execution(protocol.scala:395)<br>
     at isabelle.Protocol.discontinue_execution$(protocol.scala:306)<br>
     at isabelle.Prover.discontinue_execution(prover.scala:71)<br>
     at isabelle.Session.handle_raw_edits$1(session.scala:397)<br>
     at isabelle.Session.$init$$$anonfun$3(session.scala:648)<br>
     at <br>
isabelle.Consumer_Thread$.consume_single$1$$anonfun$1(consumer_thread.scala:28)<br>
     at isabelle.Exn$.capture(exn.scala:60)<br>
     at isabelle.Consumer_Thread$.consume_single$1(consumer_thread.scala:28)<br>
     at isabelle.Consumer_Thread$.fork$$anonfun$2(consumer_thread.scala:34)<br>
     at isabelle.Consumer_Thread.process(consumer_thread.scala:90)<br>
     at isabelle.Consumer_Thread.main_loop(consumer_thread.scala:108)<br>
     at isabelle.Consumer_Thread.$init$$$anonfun$1(consumer_thread.scala:50)<br>
     at <br>
isabelle.Consumer_Thread.$init$$$anonfun$adapted$1(consumer_thread.scala:50)<br>
     at scala.Function0.apply$mcV$sp(Function0.scala:42)<br>
     at isabelle.Isabelle_Thread$.$anonfun$2(isabelle_thread.scala:64)<br>
     at isabelle.Isabelle_Thread.run(isabelle_thread.scala:140)</p>
<ol start="2">
<li>Also observed, but only when concurrently applying the same commands <br>
with 2 or more "users":</li>
</ol>
<p>Exception in thread "event_timer"<br>
*** Consumer thread not active: "Isabelle.Session.manager"<br>
     at isabelle.Exn$ERROR$.apply(exn.scala:25)<br>
     at isabelle.Exn$.error(exn.scala:29)<br>
     at isabelle.package$.$init$$$anonfun$1(ROOT.scala:9)<br>
     at isabelle.Consumer_Thread.request(consumer_thread.scala:78)<br>
     at isabelle.Consumer_Thread.send_wait(consumer_thread.scala:118)<br>
     at isabelle.Session.update(session.scala:760)<br>
     at <br>
isabelle.Headless$Resources.load_theories$$anonfun$1(headless.scala:675)<br>
     at isabelle.Synchronized.change(synchronized.scala:67)<br>
     at isabelle.Headless$Resources.load_theories(headless.scala:676)<br>
     at <br>
isabelle.Headless$Session.check_state$1$$anonfun$3(headless.scala:338)<br>
     at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)<br>
     at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)<br>
     at scala.Option$WithFilter.foreach(Option.scala:437)<br>
     at isabelle.Headless$Session.check_state$1(headless.scala:338)<br>
     at <br>
isabelle.Headless$Session.check_progress$lzyINIT1$1$$anonfun$1(headless.scala:347)<br>
     at <br>
isabelle.Headless$Session.check_progress$lzyINIT1$1$$anonfun$adapted$1(headless.scala:349)<br>
     at scala.Function0.apply$mcV$sp(Function0.scala:42)<br>
     at isabelle.Event_Timer$$anon$1.run(event_timer.scala:28)<br>
     at java.base/java.util.TimerThread.mainLoop(Timer.java:566)<br>
     at java.base/java.util.TimerThread.run(Timer.java:516)</p>
<p>Interestingly, during testing, the specific theory for use_theories <br>
didn't seem to affect the outcome.</p>
<p>However, the exception doesn't occur if a delay of &gt;2-3 seconds is <br>
inserted between session_stop and use_theories calls. This led me to <br>
suspect a race condition, but I couldn't pinpoint the exact cause in the <br>
Server code.</p>
<p>I would greatly appreciate any advice or guidance on how to address this <br>
behavior. Is there a way to navigate the timer issues without resorting <br>
to delaying the execution on the client?</p>
<p>Best regards,<br>
Joshua Kobschätzki</p>
<p>[^0]: <a href="https://k6.io/open-source/">https://k6.io/open-source/</a></p>
<p>[^1]: <a href="https://git.tu-berlin.de/cobalt.rocks/isa-bench">https://git.tu-berlin.de/cobalt.rocks/isa-bench</a>, a MRE, if <br>
requested, can be made available</p>
<p>[^2]: Command log -- executed after successful client&lt;&gt;server handshake:</p>
<h1>executed in a loop -- exception occurred at 2-4 iteration</h1>
<p>session_start {"session": "HOL", "options": <br>
["headless_consolidate_delay=0.5", "headless_prune_delay=5", <br>
"show_states"]}\n</p>
<h1>await session start, retrieve session id</h1>
<p>use_theories {"session_id": "{{ previously retrieved session id }}", <br>
"theories": ["{{ some theory, the specific theory didn't matter during <br>
testing }}"], "master_dir": "{{ theory path }}"}\n</p>
<h1>await use_theories</h1>
<p>purge_theories {"session_id": "{{ previously retrieved session id }}", <br>
"all": true}\n</p>
<h1>await purge_theories</h1>
<p>session_stop {"session_id": "{{ previously retrieved session id }}"}\n</p>
<h1>await session_stop, if exception occurs:</h1>
<h1>FAILED {"kind": "error", "message": "java.lang.IllegalStateException:</h1>
<p>Timer already cancelled.","task": "&lt;task id for session_close&gt;"}</p>
<h1>the stack trace will be dispalyed in the corresponding server stdout</h1>



<hr><p>Last updated: Nov 01 2025 at 16:22 UTC</p>
</html>